dist: trusty
sudo: false
language: c
service:
  - docker
env:
  matrix:
    - BASE=ubuntu:14.04
    - BASE=ubuntu:16.04
    - BASE=ubuntu:18.04
    - BASE=ubuntu:devel

os:
  - linux

script:
  - |
    docker build -t build-$BASE - <<EOF
    FROM $BASE
    RUN apt-get update && apt-get install -y gcc flex bison sparse && rm -rf /var/lib/apt/lists/*
    VOLUME /source
    WORKDIR /source
    ENV CROSS_COMPILE=
    ENV ARCH powerpc
    ENV DEFCONFIG ppc64le_defconfig
    ENV KBUILD_OUTPUT build
    ENV SILENT=0
    ENV KBUILD_CHECKSRC=2
    CMD arch/powerpc/tools/ci/build.sh
    EOF
  - docker run --volume "${PWD}":/source --env JFACTOR=$(nproc) build-$BASE

