language: c
services: docker
os:
- linux-ppc64le
- linux
sudo: false

env:
  global:
    - REPO="${DOCKER_USERNAME}"

# DOCKER_USERNAME and DOCKER_PASSWORD need to be secure environment variables either above
# or in the settings within travis.

script:
- $CC -static -Os -nostartfiles -fno-asynchronous-unwind-tables -Wno-implicit-function-declaration -o hello hello.c
- docker build -t "$DOCKER_USERNAME"/hello_world:${TRAVIS_BRANCH}_${TRAVIS_OS_NAME} .
- docker images
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$REPO"/hello_world_${TRAVIS_OS_NAME}:${TRAVIS_BRANCH}

jobs:
  include:
    - stage: build
      script:
      - |
         if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           mkdir -p ~/.docker
           echo '{ "experimental" : "enabled" }' > ~/.docker/config.json
           MANIFEST="${REPO}/hello_world:${TRAVIS_BRANCH}"
           docker manifest create  "${MANIFEST}" "${REPO}/hello_world_linux:${TRAVIS_BRANCH}" "${REPO}/hello_world_linux-ppc64le:${TRAVIS_BRANCH}"
           docker manifest inspect "${MANIFEST}"
           docker manifest push    "${MANIFEST}"
         fi

# vim:set et ts=2 sw=2:
